//COMMON CONSTANTS
export const RESPONSE_CODE_SUCCESS = 1;
//TEST CONSTANTS
export const TEST_ACTION = "TEST_ACTION";
//RACERS CONSTANTS
export const ON_RACER_CLICK = "ON_RACER_CLICK";
export const STORED_RACER_CLICK = "STORED_RACER_CLICK";